[style.description]
foreground = { ansi = 15 }
underline = false
bold = false
italic = false

[style.command_name]
foreground = "yellow"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "cyan"
underline = false
bold = false
italic = false

[style.example_code]
underline = false
bold = false
italic = false

[style.example_variable]
foreground = "blue"
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 72 

[directories]
