# vim:fileencoding=utf-8:foldmethod=marker

## Examples {{{
# default
# format = """
# $username\
# $hostname\
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $fossil_branch\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $pijul_channel\
# $docker_context\
# $package\
# $c\
# $cmake\
# $cobol\
# $daml\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $golang\
# $guix_shell\
# $haskell\
# $haxe\
# $helm\
# $java\
# $julia\
# $kotlin\
# $gradle\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $purescript\
# $python\
# $raku\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $zig\
# $buf\
# $nix_shell\
# $conda\
# $meson\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $env_var\
# $crystal\
# $custom\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $os\
# $container\
# $shell\
# $character"""

# }}}

## Custom format - basic
format = """
$git_status\
$directory\
$python$c$java$lua$rust\
$character"""

add_newline = true

continuation_prompt = '[󰮺 󰮺 󰮺](black) '


## Modules
[directory]
style = 'white'
read_only = ' '
read_only_style = 'bright-red'
truncation_length = 4
truncate_to_repo = true
fish_style_pwd_dir_length = 1
format = '[$read_only]($read_only_style)[$path]($style) '
before_repo_root_style = 'bright-white'
# repo_root_style = 'underline blue'
repo_root_format = '[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) '

[character]
success_symbol = '[](bold cyan)'
error_symbol = '[](bold red)'

[fill]
symbol = ' '

[time]
disabled = true
style = 'white'
time_format = '%I:%M'
# format = '[ $time]($style)'
format = '[$time]($style)'
use_12hr = true

[username]
style_user = 'fg:cyan'
format = '[RC]($style)[](bright-black) '
# style_user = 'fg:#232A2E bg:cyan bold'
# format = '[ 󰣇 ]($style)[](cyan) '
show_always = true
disabled = false

[git_status]
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '$'
modified = '󱈸'
staged = '+'
renamed = '»'
deleted = '✘'
style = 'yellow'
format = '[](blue)([\[](bright-black)[$all_status$ahead_behind]($style)[\]](bright-black)) '

[git_branch]
style = 'blue bold'
format = '[$symbol]($style)'
# format = '([$symbol]($style))'

[git_metrics]
disabled = false
format = '([\(](bright-white)[+$added]($added_style)[/](bright-white)[-$deleted]($deleted_style)[\)](bright-white) )'

[cmd_duration]
show_milliseconds = false
format = '[󰔚](purple)[$duration](bright-white)'
min_time = 1000

[shell]
disabled = false
style = 'bright-white'

# languages
[python]
symbol = '[](bright-white)'
style = 'bright-white'
format = '[${symbol}${pyenv_prefix}(\($virtualenv\))]($style) '
detect_files = ['.python-version', 
                  'Pipfile', 
                  '__init__.py', 
                  'pyproject.toml', 
                  'requirements.txt', 
                  'setup.py', 
                  'tox.ini',
                  'pyvenv.cfg'
]
# detect_folders = ['']

[lua]
symbol = '[󰢱](bright-white)'
style = 'bright-white'
# format = '[via ](bright-white)[${symbol}${version}]($style) '
format = '(bright-white)[${symbol}]($style) '

[c]
symbol = '[](bright-white)'
style = 'bright-white'
format = '(bright-white)[${symbol}]($style) '

[java]
symbol = '[](bright-white)'
style = 'bright-white'
format = '(bright-white)[${symbol}]($style) '

[rust]
symbol = '[󱘗](bright-white)'
style = 'bright-white'
format = '(bright-white)[${symbol}]($style) '
