# vim:fileencoding=utf-8:foldmethod=marker

## Examples {{{
# default
# format = """
# $username\
# $hostname\
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $fossil_branch\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $pijul_channel\
# $docker_context\
# $package\
# $c\
# $cmake\
# $cobol\
# $daml\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $golang\
# $guix_shell\
# $haskell\
# $haxe\
# $helm\
# $java\
# $julia\
# $kotlin\
# $gradle\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $purescript\
# $python\
# $raku\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $swift\
# $terraform\
# $vlang\
# $vagrant\
# $zig\
# $buf\
# $nix_shell\
# $conda\
# $meson\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $env_var\
# $crystal\
# $custom\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $os\
# $container\
# $shell\
# $character"""

# }}}

## Custom format - basic
format = """
${custom.git_dir}\
$directory\
$python$c$java$lua$rust\
$character"""

add_newline = true

# command_timout = 500 # Default
# command_timeout = 500

continuation_prompt = '[󰮺 󰮺 󰮺](black) '

# Custom Modules
## Git
[custom.git_dir]
# disabled = true
description = "Displays name of the top level directory if inside of a git repository"
command = "reponame.sh"
when = "git rev-parse --is-inside-work-tree > /dev/null"
shell = ["bash", "--noprofile", "--norc"]
format = '[](blue)[\[](black)[$output](blue)[\]](black) '

# Starship Modules
## Basic
[directory]
style = 'white'
read_only = ' '
read_only_style = 'bright-red'
truncation_length = 4
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = '[$read_only]($read_only_style)[$path]($style) '

[character]
success_symbol = '[](bold cyan)'
error_symbol = '[](bold red)'

[cmd_duration]
show_milliseconds = false
format = '[󰔚](purple)[$duration](bright-white)'
min_time = 1000

## languages
[python]
symbol = '[](bright-white)'
style = 'bright-white'
format = '[${symbol}${pyenv_prefix}(\($virtualenv\))]($style) '
detect_files = ['.python-version', 
                  'Pipfile', 
                  '__init__.py', 
                  'pyproject.toml', 
                  'requirements.txt', 
                  'setup.py', 
                  'tox.ini',
                  'pyvenv.cfg'
]

[lua]
symbol = '[󰢱](bright-white)'
style = 'bright-white'
# format = '[via ](bright-white)[${symbol}${version}]($style) '
format = '(bright-white)[${symbol}]($style) '

[c]
symbol = '[](bright-white)'
style = 'bright-white'
format = '(bright-white)[${symbol}]($style) '

[java]
symbol = '[](bright-white)'
style = 'bright-white'
format = '(bright-white)[${symbol}]($style) '

[rust]
symbol = '[󱘗](bright-white)'
style = 'bright-white'
format = '(bright-white)[${symbol}]($style) '
