"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
shell_integration = true
enable_cursor_positioning = true
version = 3

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  type = "time"
  foreground = "white"
  style = "plain"
  template = "<black>╭╴</>{{ .CurrentDate | date .Format }}<black>╶</>"

    [blocks.segments.properties]
    time_format = "Monday 3:04 PM"


  [[blocks.segments]]
  type = "git"
  foreground = "lightBlue"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}lightYellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}lightRed{{ end }}",
  "{{ if gt .Ahead 0 }}lightMagenta{{ end }}",
  "{{ if gt .Behind 0 }}lightMagenta{{ end }}"
   ]
  style = "plain"
  template = "<black>╴</>{{ .UpstreamIcon }} {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.Modified }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true
    branch_icon = ""
    branch_identical_icon = ""

[[blocks]]
alignment = "right"
type = "prompt"
filler = "<black>─</>"

  [[blocks.segments]]
  foreground = "cyan"
  foreground_templates = [ "{{ if gt .Code 0 }}lightRed{{ end }}" ]
  style = "diamond"
  template = "<black>╴</>{{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    style = "round"
    always_enabled = true


  [[blocks.segments]]
  type = "shell"
  style = "plain"
  foreground = "white"
  template = "<d>on</d> {{ .Name }}<black>╶╮</>"

    [blocks.segments.properties.mapped_shell_names]
    pwsh = "Pwsh"
    powershell = "Pwsh"
    cmd = "Cmd"
    bash = "Bash"
    zsh = "Zsh"
    fish = "Fish"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#61AFEF"
  style = "plain"
  template = " {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    style = "full"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#E06C75"
  style = "plain"
  template = "!"
  type = "root"

  [[blocks.segments]]
  foreground = "#E06C75"
  style = "plain"
  template = "❯"
  type = "text"
